places_list = ['London', 'America', 'China', 'France']
print(places_list)
print(sorted(places_list))
print(places_list)
reverse_list = sorted(places_list, reverse = True)
print(reverse_list)
print(places_list)
places_list.reverse()
print(places_list)
places_list.reverse()
print(places_list)
places_list.sort()
print(places_list)
places_list.sort(reverse = True)
print(places_list)
length = len(places_list)
print(length)